sensors:
- sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /rgbd_camera/depth/points
  max_range: 10
  padding_offset: 0.01
  padding_scale: 1.0
  point_subsample: 1
  filtered_cloud_topic: output_cloud
# this last topic is just to debug, having it adds processing time


# sensors:
#  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
#    image_topic: /head_mount_xtion/depth/image_raw
#    queue_size: 5
#    near_clipping_plane_distance: 0.3
#    far_clipping_plane_distance: 5.0
#    skip_vertical_pixels: 1
#    skip_horizontal_pixels: 1
#    shadow_threshold: 0.2
#    padding_scale: 4.0
#    padding_offset: 0.03
#    filtered_cloud_topic: output_cloud



